### ISSUE TITLE
Allow properties without delimiters

### ISSUE THREAD

**Issue by PedroAlbR** [adjesusds/restql#1]
### User Story

As a developer, I would like to pass properties without delimiters, so that I can get the data that I am requesting.

### Conditions of Satisfaction

- I should get a response when passing a property without a delimiter.

### Dev notes

Currently, `isResolver` expects the property to include a delimiter:
https://github.com/adjesusds/restql/blob/0d4c676255f9b032b2f1f74059f3f47160ccd478/src/utils/isResolver.js#L21-L29

Specifically here:
https://github.com/adjesusds/restql/blob/0d4c676255f9b032b2f1f74059f3f47160ccd478/src/utils/isResolver.js#L24

Making this resolver invalid

```js
const resolver = { location_area_encounters: null }
// "InvalidArgumentError: invalid resolver `{\"location_area_encounters\":null}`"
```

**Comment by adjesusds** [comment]
@PedroAlbR thx for submitting this issue! 💯

You can see/test the new version here: https://www.npmjs.com/package/restql/v/1.1.6

🦄
